[theme]
base                     = "light"
primaryColor             = "#2196F3"
backgroundColor          = "#FFFFFF"
secondaryBackgroundColor = "#F1F5F9"
textColor                = "#1E293B"
font                     = "sans serif"
